### PR TITLE
Add Noetic support. Set compiler flags based on CMake version. Remove…

### PR DESCRIPTION
**Pull request by tdenewiler**
… older/deprecated OpenCV includes.

Signed-off-by: Thomas Denewiler <thomas.denewiler@navy.mil>

### CODE REVIEW

**Comment by lauralindzey** [comment]
I'm glad to see this! I had made the same changes on my system a while ago and was about to submit a PR.

**Comment by lauralindzey** [comment]
@crvogt -- these changes look good to me, and I can confirm that they compile on my 20.04 machine =)

**Review by lauralindzey — APPROVED** [review]
Compiles successfully on my 20.04 desktop.

**Review by crvogt — APPROVED** [review]
Compiles and runs fine on 18.04/Melodic/Gazebo9.

No runtime errors and tested with `roslaunch gtri_based_fls blueview_basement_cylinder.launch`

Thanks @tdenewiler  @lauralindzey

**Pull request merged**
